vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        recipe_images:
            uri_prefix: /images/Art_Vehi
            upload_destination: '%kernel.project_dir%/public/images/Art_Vehi'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
